name: Merge and Synchronize to remote directory
run-name: Merge and Sync repo to remote directory
on: push

jobs:
  merge-and-sync-to-remote-dir:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
    - name: Checkout
      uses: emiliensocchi/actions@checkout
    - name: Merge and commit
      uses: emiliensocchi/actions@merge-queries-and-commit
      with:
        user_email: 'emilien.socchi@gmail.com'
        user_name: 'emiliensocchi'
    - name: Push remotely
      uses: emiliensocchi/actions@sync-to-remote-file
      with:
        source_file: 'customqueries.json'
        destination_file: 'Tools/azurehound/customqueries.json'
        destination_repo: 'emiliensocchi/azure-hunting'
        user_email: 'emilien.socchi@gmail.com'
        user_name: 'emiliensocchi'