name: Merge and Synchronize to remote directory
run-name: Merge and Sync repo to remote directory
on: push

jobs:
  merge-and-sync-to-remote-dir:
    runs-on: ubuntu-latest
    env:
      API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    steps:
    - name: Checkout
      uses: emiliensocchi/actions@checkout
    - name: Merge
      run: |
        bash ./.github/workflows/merge.sh
        git add .
        git commit --message "Merge queries"
        git push -u origin HEAD:main
    - name: Push locally
      uses: emiliensocchi/actions@sync-to-remote-file
      with:
        source_file: 'customqueries.json'
        destination_file: 'customqueries.json'
        destination_repo: 'emiliensocchi/azurehound-cipher-queries'
        user_email: 'emilien.socchi@gmail.com'
        user_name: 'emiliensocchi'
    - name: Push remotely
      uses: emiliensocchi/actions@sync-to-remote-file
      with:
        source_file: 'customqueries.json'
        destination_file: 'Tools/azurehound/customqueries.json'
        destination_repo: 'emiliensocchi/azure-hunting'
        user_email: 'emilien.socchi@gmail.com'
        user_name: 'emiliensocchi'